---                                                                                                             
- hosts: all
  become_user: root
  vars:
    remove_users:
      #- "adminhk"
      #- "adminre"
      - "cain.chen"
 
  tasks:
    - name: "Remove user accounts"
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      with_items: "{{ remove_users }}"
 
    - name: "Remove user from sudoers"
      lineinfile:
        path: /etc/sudoers.d/twops
        line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
        state: absent
        validate: 'visudo -c -f %s'
      with_items: "{{ remove_users }}"
