---                                                                                                             
- hosts: 127.0.0.1
  become_user: root                                                                                              
#  connection: "local"
  vars:
    users:
    #-  "cain.chen"
    #-  "jack.wu"
    -  "ayo.tseng"
  tasks:
  - name: "Create user accounts and add users to groups"
    user:
      name: "{{ item }}"
#      groups: "admin,www-data"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
#      key: "{{ lookup('file', 'files/'+ item + '/tmp/{{ item }}.pub') }}"
      key: "{{ lookup('file', '/opt/devops/key/{{ item }}.pub') }}"
    with_items: "{{ users }}"
  - name: Add user user to sudo
    lineinfile:
        path: /etc/sudoers.d/twops
        line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
        state: present
#        owner: root 
#        group: root 
        mode: "0440"
        create: yes
        validate: 'visudo -c -f %s'
    with_items: "{{ users }}"
